FROM node:18

WORKDIR /app

# Copier package.json
COPY package.json ./

# Installer les dépendances
RUN npm install

# Copier le reste (sera écrasé par le volume au runtime, mais ok pour le build)
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]