services:
  mon-app-react:
     image: mon-app-react
     ports:
      - '3000:3000'
     container_name: react

  fastapi:
    image: fastapi
    ports:
      - '80:80'
    container_name: fastapi

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=appdb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

networks:
  default:
    name: app_network
